from pathlib import Path


def replace_exact(path, old, new, expected=1):
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != expected:
        raise SystemExit(f"{path}: expected {expected} exact matches, found {count}")
    p.write_text(text.replace(old, new))


replace_exact(
    "app/build.gradle",
    '''        // Smart S Launcher 3.30.67 - exact notification-event history and unread bell state\n        versionCode 495\n        versionName "3.30.67"''',
    '''        // Smart S Launcher 3.30.68 - edge-to-edge history viewport and bounded card expansion\n        versionCode 496\n        versionName "3.30.68"''')

replace_exact(
    "app/src/main/res/layout/main.xml",
    '''        android:layout_alignParentStart="true"\n        android:layout_alignParentTop="false"\n        android:layout_marginStart="@dimen/list_margin_horizontal"\n        android:layout_marginLeft="@dimen/list_margin_horizontal"\n        android:layout_marginEnd="@dimen/list_margin_horizontal"\n        android:layout_marginRight="@dimen/list_margin_horizontal"\n        android:layout_marginBottom="10dp"''',
    '''        android:layout_alignParentStart="true"\n        android:layout_alignParentTop="false"\n        android:layout_marginBottom="10dp"''')

controller = "app/src/main/java/fr/neamar/kiss/forwarder/VerticalCardGroupResizeController.java"
replace_exact(
    controller,
    '''import android.widget.SeekBar;\nimport android.widget.TextView;''',
    '''import android.widget.ScrollView;\nimport android.widget.SeekBar;\nimport android.widget.TextView;''')

replace_exact(
    controller,
    '''    private void applyWidthToAllCards() {\n        if (!isEnabled() || column == null || column.getWidth() <= 0) return;\n        int widthPercent = prefInt(PREF_WIDTH, 100, MIN_WIDTH, MAX_WIDTH);\n        int available = Math.max(dp(120), column.getWidth() - column.getPaddingLeft()\n                - column.getPaddingRight());\n        int targetWidth = Math.round(available * widthPercent / 100f);\n\n        for (int i = 0; i < column.getChildCount(); i++) {\n            View child = column.getChildAt(i);\n            ViewGroup.LayoutParams raw = child.getLayoutParams();\n            if (!(raw instanceof LinearLayout.LayoutParams)) continue;\n            LinearLayout.LayoutParams lp = (LinearLayout.LayoutParams) raw;\n            // Keep 100% as the exact historical full-width behaviour. Values above 100% are\n            // deliberate oversized card widths rather than being collapsed back to MATCH_PARENT.\n            int desired = widthPercent == 100\n                    ? ViewGroup.LayoutParams.MATCH_PARENT : targetWidth;\n            if (lp.width == desired && lp.gravity == Gravity.CENTER_HORIZONTAL) continue;\n            lp.width = desired;\n            lp.gravity = Gravity.CENTER_HORIZONTAL;\n            child.setLayoutParams(lp);\n        }\n    }''',
    '''    private void applyWidthToAllCards() {\n        if (!isEnabled() || column == null) return;\n        int widthPercent = prefInt(PREF_WIDTH, 100, MIN_WIDTH, MAX_WIDTH);\n\n        // Above 100%, consume the renderer's own horizontal gutters instead of creating a child\n        // wider than its viewport. At 200% every Vertical Card can use the complete result width\n        // without being centered behind (and clipped by) a narrower ScrollView.\n        ScrollView scroller = cardForwarder.getScroller();\n        int scrollerInset = VerticalCardWidthPolicy.insetForPercent(dp(8), widthPercent);\n        if (scroller != null\n                && (scroller.getPaddingLeft() != scrollerInset\n                || scroller.getPaddingRight() != scrollerInset)) {\n            scroller.setPadding(scrollerInset, scroller.getPaddingTop(),\n                    scrollerInset, scroller.getPaddingBottom());\n        }\n\n        if (column.getWidth() <= 0) return;\n        int available = Math.max(dp(120), column.getWidth() - column.getPaddingLeft()\n                - column.getPaddingRight());\n        int targetWidth = VerticalCardWidthPolicy.targetWidth(available, widthPercent);\n        int wrapperInset = VerticalCardWidthPolicy.insetForPercent(dp(4), widthPercent);\n        int cardInset = VerticalCardWidthPolicy.insetForPercent(dp(4), widthPercent);\n\n        for (int i = 0; i < column.getChildCount(); i++) {\n            View child = column.getChildAt(i);\n            ViewGroup.LayoutParams raw = child.getLayoutParams();\n            if (!(raw instanceof LinearLayout.LayoutParams)) continue;\n            LinearLayout.LayoutParams lp = (LinearLayout.LayoutParams) raw;\n            int desired = widthPercent >= 100\n                    ? ViewGroup.LayoutParams.MATCH_PARENT : targetWidth;\n            boolean wrapperChanged = lp.width != desired\n                    || lp.gravity != Gravity.CENTER_HORIZONTAL\n                    || lp.leftMargin != wrapperInset\n                    || lp.rightMargin != wrapperInset;\n            if (wrapperChanged) {\n                lp.width = desired;\n                lp.gravity = Gravity.CENTER_HORIZONTAL;\n                lp.leftMargin = wrapperInset;\n                lp.rightMargin = wrapperInset;\n                child.setLayoutParams(lp);\n            }\n\n            if (!(child instanceof ViewGroup) || ((ViewGroup) child).getChildCount() == 0) continue;\n            View card = ((ViewGroup) child).getChildAt(0);\n            ViewGroup.LayoutParams cardRaw = card.getLayoutParams();\n            if (!(cardRaw instanceof LinearLayout.LayoutParams)) continue;\n            LinearLayout.LayoutParams cardLp = (LinearLayout.LayoutParams) cardRaw;\n            if (cardLp.leftMargin != cardInset || cardLp.rightMargin != cardInset) {\n                cardLp.leftMargin = cardInset;\n                cardLp.rightMargin = cardInset;\n                card.setLayoutParams(cardLp);\n            }\n        }\n    }''')

policy = Path("app/src/main/java/fr/neamar/kiss/forwarder/VerticalCardWidthPolicy.java")
if policy.exists():
    raise SystemExit(f"{policy}: already exists")
policy.write_text('''package fr.neamar.kiss.forwarder;\n\n/** Pure sizing rules for the Vertical Cards width editor. */\nfinal class VerticalCardWidthPolicy {\n    private static final int NORMAL_PERCENT = 100;\n    private static final int MAX_PERCENT = 200;\n\n    private VerticalCardWidthPolicy() { }\n\n    static int targetWidth(int availablePx, int widthPercent) {\n        if (availablePx <= 0) return 0;\n        int percent = Math.max(1, Math.min(MAX_PERCENT, widthPercent));\n        if (percent >= NORMAL_PERCENT) return availablePx;\n        return Math.max(1, Math.round(availablePx * percent / 100f));\n    }\n\n    /**\n     * Width above 100% progressively releases an existing horizontal inset. 200% means the inset\n     * is fully consumed; it never means creating a view twice as wide as the physical viewport.\n     */\n    static int insetForPercent(int baseInsetPx, int widthPercent) {\n        if (baseInsetPx <= 0) return 0;\n        int percent = Math.max(1, Math.min(MAX_PERCENT, widthPercent));\n        if (percent <= NORMAL_PERCENT) return baseInsetPx;\n        float remaining = (MAX_PERCENT - percent) / 100f;\n        return Math.max(0, Math.round(baseInsetPx * remaining));\n    }\n}\n''')

test = Path("app/src/test/java/fr/neamar/kiss/forwarder/VerticalCardWidthPolicyTest.java")
if test.exists():
    raise SystemExit(f"{test}: already exists")
test.write_text('''package fr.neamar.kiss.forwarder;\n\nimport static org.junit.Assert.assertEquals;\n\nimport org.junit.Test;\n\npublic class VerticalCardWidthPolicyTest {\n    @Test\n    public void belowOneHundredShrinksCardButKeepsBaseInsets() {\n        assertEquals(480, VerticalCardWidthPolicy.targetWidth(1000, 48));\n        assertEquals(8, VerticalCardWidthPolicy.insetForPercent(8, 48));\n        assertEquals(4, VerticalCardWidthPolicy.insetForPercent(4, 48));\n    }\n\n    @Test\n    public void oneHundredUsesViewportWithoutChangingNormalInsets() {\n        assertEquals(1000, VerticalCardWidthPolicy.targetWidth(1000, 100));\n        assertEquals(8, VerticalCardWidthPolicy.insetForPercent(8, 100));\n        assertEquals(4, VerticalCardWidthPolicy.insetForPercent(4, 100));\n    }\n\n    @Test\n    public void oneHundredFiftyUsesFullViewportAndHalfInsets() {\n        assertEquals(1000, VerticalCardWidthPolicy.targetWidth(1000, 150));\n        assertEquals(4, VerticalCardWidthPolicy.insetForPercent(8, 150));\n        assertEquals(2, VerticalCardWidthPolicy.insetForPercent(4, 150));\n    }\n\n    @Test\n    public void twoHundredUsesFullViewportWithNoInternalSideGutter() {\n        assertEquals(1000, VerticalCardWidthPolicy.targetWidth(1000, 200));\n        assertEquals(0, VerticalCardWidthPolicy.insetForPercent(8, 200));\n        assertEquals(0, VerticalCardWidthPolicy.insetForPercent(4, 200));\n    }\n\n    @Test\n    public void valuesAboveMaximumCannotCreateOffscreenWidth() {\n        assertEquals(1000, VerticalCardWidthPolicy.targetWidth(1000, 500));\n        assertEquals(0, VerticalCardWidthPolicy.insetForPercent(8, 500));\n    }\n}\n''')
