Categories:
  - Launcher
License: GPL-3.0-only
SourceCode: https://github.com/tbzmike/smart-s-launcher
IssueTracker: https://github.com/tbzmike/smart-s-launcher/issues

RepoType: git
Repo: https://github.com/tbzmike/smart-s-launcher.git

Builds:
  - versionName: 3.29.83
    versionCode: 411
    commit: 0ba5b9290d4b093ee04cf1b423652444d99b4486
    subdir: app
    gradle:
      - yes
    scandelete:
      - app/debug.keystore

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 3.29.83
CurrentVersionCode: 411
