Categories:
  - System
License: GPL-3.0-only
SourceCode: https://github.com/tbzmike/smart-s-launcher
IssueTracker: https://github.com/tbzmike/smart-s-launcher/issues

RepoType: git
Repo: https://github.com/tbzmike/smart-s-launcher.git

Builds:
  - versionName: 3.29.83
    versionCode: 411
    commit: 7f2d49fe31a22f95703a69f33a0c622a8d978f10
    subdir: app
    gradle:
      - yes
    scandelete:
      - app/debug.keystore

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 3.29.83
CurrentVersionCode: 411
